### ISSUE TITLE
Multiple single quotes break syntax highlight

### ISSUE THREAD

**Issue by lukepass** [stephpy/vim-yaml#13]
Hello, I noticed that multiple single quotes on the same line break syntax highlight:

![image](https://user-images.githubusercontent.com/6429961/34992435-828bbef4-facd-11e7-9f2f-a1b575607f7c.png)

How can I solve this?

Thanks.

**Comment by stephpy** [comment]
Hi, it's related to: https://github.com/stephpy/vim-yaml/pull/12

**Comment by stephpy** [comment]
I merged it.
