### ISSUE TITLE
bad syntax highlighting when `:` inside string

### ISSUE THREAD

**Issue by jgallen23** [stephpy/vim-yaml#6]
![screenshot 2017-04-10 at 9 20 51 am](https://cloud.githubusercontent.com/assets/27936/24871618/09e3d206-1dcf-11e7-9b50-deae41bad851.png)

**Comment by KibaFox** [comment]
I'm experiencing this as well.

**Comment by jgallen23** [comment]
I'm still having this issue.  Looks like its fine in values, but breaks when values in arrays have quotes

![screenshot 2017-07-04 at 8 13 25 am](https://user-images.githubusercontent.com/27936/27835643-af498552-6090-11e7-944f-f185b5557275.png)

I had to go back to 6430c84
